<!DOCTYPE html>
<html lang="en">
  <head>
		<link rel="shortcut icon" href="../img/mangowhite.png">
  	<title>ManGO | IT Shop for you</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="css/mango.css">
    <script src="js/mango.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
       :target {
        animation: highlight 1s ease;
       }
    </style>

  </head>


  <body>

    <nav>
    <a href="#onexxxxxxxxxxxxxx">1</a>
    <a href="#two">2</a>
    <a href="#three">3</a>
  </nav>

  <section>
    <div id="onexxxxxxxxxxxxxxz"><h2>One</h2>Pellentesque habitant morbi ...Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.</div>
    <div id="two"><h2>Two</h2>Pellentesque habitant morbi ...Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.</div>
    <div id="onexxxxxxxxxxxxxx"><h2>Three</h2>Pellentesque habitant morbi ...Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.Framework. Starter template. Nothing but the basics: compiled CSS and JavaScript. Grids. Multiple examples of grid layouts with all four tiers, nesting, and more. Jumbotron. Build around the jumbotron with a navbar and some basic grid columns. Narrow jumbotron.</div>
  </section>​

	</body>
</html>
